services:
  point_transformer:
    image: rkhafizov.point_transformer_image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rkhafizov.point_transformer_container
    network_mode: host
    ipc: host
    volumes:
      - /home/r.khafizov/point_transformer3/Pointcept:/workspace/Pointcept
      - /home/r.khafizov/point_transformer3/PointTransformerV3:/workspace/PointTransformerV3
    ports:
      - "6666:6666"  # Adjust the port mapping as needed
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Adjust GPU visibility as needed
    command: "/bin/bash -c 'source /etc/bash.bashrc && tail -f /dev/null && /bin/bash'"  # Keep container running
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # count: 1
            device_ids: ["1"]
            capabilities: [gpu]
